services:
  - type: web
    name: deepface-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 33.10.13

